name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        
      - name: Build for Production
        run: npm run build -- --configuration=production --output-path=dist/traffic-finding/browser

      - name: Ensure Deployment Directory Exists
        run: |
          sudo mkdir -p /home/admin-kube/actions-runner-front/_work/TrafficCheck/TrafficCheck/dist/traffic-finding/

      - name: Deploy Application
        run: |
          sudo rm -rf /home/admin-kube/actions-runner-front/_work/TrafficCheck/TrafficCheck/dist/traffic-finding/browser
          sudo cp -r dist/traffic-finding/browser /home/admin-kube/actions-runner-front/_work/TrafficCheck/TrafficCheck/dist/traffic-finding/

      - name: Set Correct Permissions
        run: sudo chown -R www-data:www-data /home/admin-kube/actions-runner-front/_work/TrafficCheck/TrafficCheck/dist

      - name: Restart Nginx
        run: sudo systemctl restart nginx


