name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        
      - name: Build for Production
        run: |
          npm run build -- --configuration=production --output-path=dist/traffic-finding
          if [ ! -d "dist/traffic-finding" ]; then
            echo "❌ Build failed! 'dist/traffic-finding' folder is missing."
            exit 1
          fi

      - name: Ensure Deployment Directory Exists
        run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S mkdir -p /home/admin-kube/actions-runner-front/_work/TrafficCheck/TrafficCheck/dist/traffic-finding/

      - name: Deploy Application
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S rm -rf /home/admin-kube/actions-runner-front/_work/TrafficCheck/TrafficCheck/dist/traffic-finding/browser
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S cp -r dist/traffic-finding/browser /home/admin-kube/actions-runner-front/_work/TrafficCheck/TrafficCheck/dist/traffic-finding/

      - name: Set Correct Permissions
        run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S chown -R www-data:www-data /home/admin-kube/actions-runner-front/_work/TrafficCheck/TrafficCheck/dist

      - name: Restart Nginx
        run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
